coin/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from money.views import MoneyListView

urlpatterns = [
    url(
        r'^admin/',
        admin.site.urls),

    url(
        r'^api/',
        include('money.urls')),

    #provisorio
    url(
        r'$',
        MoneyListView.as_view(),
        name="index"),
]

money/urls.py
from django.conf.urls import url
from .views import MoneyListJson
from .views import MoneyCreateJson
from .views import MoneyUpdateJson
from .views import MoneyDeleteJson
from .views import MoneyListView
from .views import MoneyListDatatableJson

app_name = 'money'

urlpatterns = [

    url(
        r'moneys/$',
        MoneyListJson.as_view(),
        name="moneys"),

    url(
        r'create_money/$',
        MoneyCreateJson.as_view(),
        name="create_money"),

    url(
        r'update_money/(?P<money_id>[0-9]+)/$',
        MoneyUpdateJson.as_view(),
        name="update_money"),

    url(
        r'delete_money/(?P<money_id>[0-9]+)/$',
        MoneyDeleteJson.as_view(),
        name="delete_money"),

    url(
        r'moneys-index/$',
        MoneyListView.as_view(),
        name="moneys_index"),

    url(
        r'moneys-datatables-list/$',
        MoneyListDatatableJson.as_view(),
        name="moneys_datatables_list"),

]

money/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils.translation import ugettext as _
from django.contrib.auth.models import User
from uuid import uuid4


class MoneyManager(models.Manager):

    def get_queryset(self, *args, **kwargs):
        return super(MoneyManager, self).get_queryset(
            *args, **kwargs).filter(active=True)


class Money(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    name = models.CharField(_("nombre"), max_length=100)
    symbol = models.CharField(_("símbolo"), max_length=4)
    active = models.BooleanField(_("activo"), default=True)

    objects = MoneyManager()

    class Meta:
        verbose_name = "Moneda"
        verbose_name_plural = "Monedas"

        permissions = (
            ("view_money_list", "Can see available moneys"),
            ("change_money_status", "Can change the status of moneys"),
        )

    def __str__(self):
        return self.name

    def as_json(self, parameter=None):
        return {
            "name": self.name,
            "symbol": self.symbol,
        }

    def as_json_datatable(self, parameter=None):
        return [
            self.name,
            self.symbol
        ]

    def delete(self, *args, **kwargs):
        self.active = False
        super(Money, self).save(*args, **kwargs)


class Wallet(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    name = models.CharField(_("Nombre"), max_length=200)
    money = models.ForeignKey(Money, verbose_name="Moneda")
    credit = models.DecimalField(decimal_places=20, max_digits=30)
    owner = models.ForeignKey(User, verbose_name="Propietario")

    def as_json(self, parameter=None):
        return {
            "name": self.name,
            "money": self.money.as_json(),
            "credit": str(self.credit),
            "owner": self.owner.username,
        }


class Operation(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    from_wallet = models.ForeignKey(
        Wallet, verbose_name="Billetera Origen", related_name="from_wallet")
    to_wallet = models.ForeignKey(
        Wallet, verbose_name="Billetera Destino", related_name="to_wallet")
    amount = models.DecimalField(decimal_places=20, max_digits=30)

    def as_json(self, parameter=None):
        return {
            "created": self.created.strftime("%Y-%m-%d %H:%M:%S"),
            "from_wallet": self.from_wallet.as_json(),
            "to_wallet": self.to_wallet.as_json(),
            "amount": str(self.amount)
        }

money/forms.py
from django import forms
from .models import Money


class MoneyCreateForm(forms.ModelForm):

    class Meta:
        model = Money
        fields = ['name', 'symbol', ]


class MoneyUpdateForm(MoneyCreateForm):

    def __init__(self, *args, **kwargs):
        super(MoneyUpdateForm, self).__init__(*args, **kwargs)
        self.fields['name'].required = True
        self.fields['symbol'].required = True

money/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import get_object_or_404
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required

from coin.datatables import DatatableAsync
from coin.serializers import JSONResponseMixin
from django.views.generic.list import ListView

from .models import Money
from .forms import MoneyCreateForm
from .forms import MoneyUpdateForm


@method_decorator(login_required, name='dispatch')
@method_decorator(
    permission_required('money.view_money_list'), name='dispatch')
class MoneyListJson(JSONResponseMixin):
    model = Money


@method_decorator(login_required, name='dispatch')
@method_decorator(
    permission_required('money.change_money_status'), name='dispatch')
class MoneyCreateJson(JSONResponseMixin):
    model = Money
    form_class = MoneyCreateForm


@method_decorator(login_required, name='dispatch')
@method_decorator(
    permission_required('money.change_money_status'), name='dispatch')
class MoneyUpdateJson(JSONResponseMixin):
    model = Money
    form_class = MoneyUpdateForm


@method_decorator(login_required, name='dispatch')
@method_decorator(
    permission_required('money.change_money_status'), name='dispatch')
class MoneyDeleteJson(JSONResponseMixin):
    model = Money

    def post(self, request, *args, **kwargs):
        pk = kwargs["money_id"]
        money = get_object_or_404(self.model, pk=pk)
        money.delete()
        return self.send_response([])


class MoneyListView(ListView):
    model = Money


"""
@method_decorator(login_required, name='dispatch')
@method_decorator(
    permission_required('money.view_money_list'), name='dispatch')
"""
class MoneyListDatatableJson(JSONResponseMixin):

    method_json = "as_json_datatable"

    def get(self, request, *args, **kwargs):

        datatable = DatatableAsync(
            Money,
            fields_orders=[
                'name',
                'symbol',
            ],
            fields_filters=[
                'name',
                'symbol',
            ],
            method_json=self.method_json
        )

        return datatable.get_result(request)

money/templates/money/money_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Listado de Monedas {% endblock %}

{% block moneys_active %} active {% endblock %}

{% block head %}
      <script src="{% static 'js/fa.js' %}"></script>

{% endblock%}
{%block section%}
  <section class="content-header">
    <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-home"></i> Home</a></li>
        <li class="active">Monedas</li>
      </ol>
  </section>
  <br>
  <section class="content">
    <div class="box box-info">
        <div class="box-header with-border">
            <h3 class="box-title">Monedas</h3>
        </div>
      <div class="box-body">
        <div class="row">
          <div class="col-md-9">
            <div class="table-responsive">
          <table id="moneys" class="table table-striped table-hover table-condensed display responsive" cellspacing="0" width="100%">
            <thead >
              <tr class="info">               
                <th>Nombre</th>
                <th>Símbolo</th>
              </tr>
            </thead>
          </table>
            </div>
          </div>
  	  </div>
    </section>
{% endblock %}

{% block javascript %}
  <link rel="stylesheet" type="text/css" href="{% static 'datatables/css/uikit.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="{% static 'datatables/css/dataTables.uikit.min.css' %}"/>
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/responsive/2.1.0/css/responsive.dataTables.min.css">

  <script type="text/javascript" src="{% static 'datatables/js/jquery.dataTables.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'datatables/js/dataTables.uikit.min.js' %}"></script>
  <script type="text/javascript" src="https://cdn.datatables.net/responsive/2.1.0/js/dataTables.responsive.min.js"></script>


  <script type="text/javascript">

    //var csrftoken = "{{ csrf_token }}"
    $(document).ready(function(){
      var table = $('#moneys').dataTable({
      "destroy": true,
      "scrollCollapse": true,
      "responsive":true,
      "bProcessing": true,
      "sAjaxSource": "{% url 'money:moneys_datatables_list' %}",
      "bServerSide": true,
      "bFilter": true,
      "paging": true,
      "lengthChange": true,
      "searching": true,
      "ordering": true,
      "info": true,
      "autoWidth": true,
      "select": true,
      "language":{
          "decimal":        "",
          "emptyTable":     "Sin datos para mostrar",
          "info":           "",
          "infoEmpty":      "",
          "infoFiltered":   "(filtrado desde _MAX_ filas)",
          "infoPostFix":    "",
          "thousands":      ",",
          "lengthMenu":     "Mostrar _MENU_ filas",
          "faceoadingRecords": "Cargando...",
          "processing":     "Procesando...",
          "search":         "Buscar: ",
          "zeroRecords":    "0 resultados",
          "paginate": {
              "first":      "Primero",
              "last":       "Ultimo",
              "next":       "Siguiente",
              "previous":   "Anterior"
            },
            "aria": {
              "sortAscending":  ": activate to sort column ascending",
              "sortDescending": ": activate to sort column descending"
            },       
        },
        "aoColumns": [
          null,
          null,
          //{ "bSortable": false }
        ],          
    });

    })
    
  </script>
{% endblock %}

templates/base.html
<!DOCTYPE HTML>
<HTML lang='es'>
	<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Material Design fonts -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'dist/css/fonts.css' %}" type="text/css">
    <link href="{% static 'dist/css/material_font.css' %}" rel="stylesheet">
    <!-- Bootstrap -->
    <!--<link href="/static/dist/css/bootstrap.min.css" rel="stylesheet">-->
    
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="{% static 'lte/bootstrap_lte/css/bootstrap.min.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <!-- <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"> -->
    <!-- Theme style -->
    
    <link rel="stylesheet" href="{% static 'lte/dist/css/infopool.min.css' %}">  
  
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    
    <script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
    <!-- jQuery 2.1.4 -->
    <script src="{% static 'lte/plugins/jQuery/jQuery-2.1.4.min.js' %}"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="{% static 'lte/bootstrap_lte/js/bootstrap.min.js' %}"></script>
  
    <link rel="stylesheet" href="{% static 'lte/bootstrap_lte/css/bootstrap-dialog.min.css' %}">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap3-dialog/1.34.7/js/bootstrap-dialog.min.js"></script>

    <script src="{% static 'lte/js/mousetrap.js' %}"></script>
    <script src="{% static 'lte/js/mousetrap.min.js' %}"></script>

    <title>
      {% block title %}{% endblock %}
    </title>
    
    {% block head %}
    {% endblock %}

    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
  </head>
	
  <body id ="body" class="hold-transition skin-blue sidebar-mini fixed " style="font-family: 'Open Sans', sans-serif;">			

      <div class="wrapper">
        
        <header class="main-header" >
          <!-- Logo -->
          <a href="#" class="logo" >
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>R</b>P</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Ripio</b></span>
          </a>
          <!-- Header Navbar: style can be found in header.less -->
          <nav class="navbar navbar-static-top" role="navigation" >
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button"   id="sidebar-toggle">
              <span class="sr-only">Toggle navigation</span>
            </a>

            <div class="navbar-custom-menu">
                <ul class="nav navbar-nav">
                  {% include 'user.html' %}
                </ul>
              </div>
          </nav>
        </header>

        <aside class="main-sidebar" >

          <section class="sidebar" >

            <ul class="sidebar-menu">
              
                <li class="header">Menú Principal</li>
                  {#% if user_permissions %#}

                    <li {% block moneys_active %}{% endblock %}>
                        <a href="{#% url 'money:' %#}" id="money"><i class="fa fa-money "></i><span>Monedas</span></a>
                    </li>
                    <li {% block wallets_active %}{% endblock %}>
                        <a href="{#% url 'moneys:' %#}" id="wallets"><i class="fa fa-shopping-bag"></i><span>Billeteras</span></a>
                    </li>

                  {#% else %#}
                    <!--
                    <li  {% block wallets_user_active %}{% endblock %}>
                        <a href="{#% url 'moneys:' %#}" id="wallets"><i class="fa fa-address-book"></i><span>Billeteras</span></a>
                    </li>-->
                    <li  {% block send_money_active %}{% endblock %}>
                        <a href="{#% url 'budgets:budget-list' %#}" id="wallets"><i class="fa fa-exchange"></i><span>Enviar Dinero</span></a>
                    </li>

                  {#% endif %#}

            </ul>
          </section>

        </aside>

        <div class="content-wrapper">
            {%block section%}
            {%endblock%}
          
        </div><!-- /.content-wrapper -->
              
      </div><!-- ./wrapper -->

        
      <!-- SlimScroll -->
      <script src="{% static 'lte/plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
      <!-- FastClick -->
      <script src="{% static 'lte/plugins/fastclick/fastclick.min.js' %}"></script>
      <!-- AdminLTE App -->
      <script src="{% static 'lte/dist/js/app.min.js' %}"></script>
      <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
      <script src="{% static 'js/bootstrap-notify/bootstrap-notify.min.js' %}"></script>

      <script type="text/javascript">
        function getCookie(name) {
            var cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                    var cookie = jQuery.trim(cookies[i]);
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }

        var csrftoken = getCookie('csrftoken');

        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
      </script>
      {% block javascript %}
      {% endblock %}
  </body>
</HTML>
		   
        




			

											

							

		
		
		
	

templates/user.html
{% load static %}
<li class="dropdown user user-menu">

  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
    <img src="{% static 'dist/img/generic.png' %}" class="user-image" alt="User Image">
    <span class="hidden-xs">Hola {{user.first_name}}</span>
  </a>
  <ul class="dropdown-menu">
    <!-- User image -->
    <li class="user-header">
      <img src="{% static 'dist/img/generic.png' %}" class="img-circle" alt="User Image">
      <p>
        {{user.first_name}} {{user.last_name}}
        <small>Eres miembro desde el {{user.date_joined | date:"d/m/Y"}}</small>
      </p>
    </li>
    
    <!-- Menu Footer-->
    <li class="user-footer">
      <div class="pull-left">
        <a href="{#% url 'login:profile'%#}" class="btn btn-info btn-flat">Perfil</a>
      </div>
      <div class="pull-right">
        <a href="{#% url 'login:panel-logout'%#}" class="btn btn-danger btn-flat">Cerrar Sesión</a>
      </div>
    </li>
  </ul>
 
</li>